//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectPSD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transaction()
        {
            this.transaction_details = new HashSet<transaction_details>();
        }
    
        public string Id { get; set; }
        public string user_id { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string payment_id { get; set; }
        public string status { get; set; }
        public string address { get; set; }
        public bool assurance { get; set; }
    
        public virtual payment payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction_details> transaction_details { get; set; }
        public virtual user user { get; set; }
    }
}
